site_name: pyDARN Documentation
repo_url: https://github.com/superdarn/pydarn
theme: readthedocs
markdown_extensions:
    - extra
    - admonition
    - toc

nav:
    - Home: index.md
    - Installation: user/install.md  
    - SuperDARN Data Access: user/superdarn_data.md 
    - Citing: user/citing.md
    - Tutorials:
            - Radar and Hardware Information: user/hardware.md 
            - Reading Files: user/io.md
            - Range-Time plots: user/range_time.md 
            - Time-Series plots: user/time_series.md 
            - Summary plots: user/summary.md
            - Fan plots: user/fan.md
            - Power plots: user/power.md
            - ACF plots: user/acf.md
            - Logging: user/logging.md
    - pyDARN Team:
        - Copyright and Licensing: dev/copyright_license.md
        - Workflow:
                - Projects: dev/projects.md
                - Issues: dev/issues.md
                - Branches: dev/branching.md
                - Pull Requests: dev/PR.md 
                - Testing: dev/testing.md
                - Code Reviews: dev/code_review.md
        - Release Guidelines: dev/releases.md
