name: flake8

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1
    - name: Lint with flake8
      run: |
        pip3 install flake8
        pip3 install --upgrade flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8
